language: php

# Should work on 5.3 and maybe even 5.2,
# but Travis errors out because it doesn't know how to test with them.

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

addons:
  postgresql: "9.3"

before_script:
  - make test/db-scripts/create-database.sql
  - psql -U postgres -v ON_ERROR_STOP=1 <test/db-scripts/create-database.sql

install: make test-dependencies

script: make run-unit-tests
